name: minesweeperislands
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wave: 0.2.2
  audioplayers: 6.0.0
  url_launcher: 6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_background: "#72E1E8"
  adaptive_icon_foreground: "assets/icon/icon_cropped.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/pirate_icon_positive.png
    - assets/images/pirate_icon_negative.png

  fonts:
    - family: Chekharda
      fonts:
        - asset: assets/fonts/Chekharda.ttf
    - family: RoadRage
      fonts:
        - asset: assets/fonts/RoadRage.otf
